### ISSUE TITLE
새로운 Item 제안2 - 김종광

### ISSUE THREAD

**Issue by jongkwang** [etherstudy/interface#3]
# 새로운 Item 제안2 - 김종광

## Goal
- 분과 프로젝트 목표는 작게
- 달성은 120% 하도록 !!
- 목표를 아주 작게 잡아 봤습니다.

## 제안
- Ethereum Wallet 기본 기능에다가
- "주소록" 기능을 추가 합니다.
  - 은행앱에 있는 "주소록" 기능
- "수신자" 확인 기능을 추가 합니다. 
  - "수신자 Address"만 넣으면
      - 과거 이력및 주소록을 통해 "수신자 이름 표시"
      - 옳바른 주소인지 검증 해줌
      - 대부분의 Banking App 에서 제공하는 수준의 기능을 제공

## 이유
- 너무 거창한것 만들지 말고... (실제로 개발 해보면 다들 참석이 어려워서 진도 나가기 힘들거든요)
- 꼭 필요한 기능만 만들자는 취지 입니다

**Comment by csy1204** [comment]
주소록
- 최근 보낸 주소에 별칭 추가 기능

수신자
- 수신자가 과거에 보낸 이력을 바탕으로 어느 거래소 주소인지 알려주는 기능

(New) 남기고 싶은 말
1. TxData를 이용해서 상대방에게 남기고 싶은 말 적기, 한글을 Hex로 변환하기만 하면 될 거 같아요
2. 다른 사람도 모두 볼 수 있다는게 단점아닌 단점

거창하기보단 정말 꼭 필요한 걸 만든다는게 좋은 것 같아요. 거기에 재밌고 간단한 기능정도만 ㅎㅎ
플랫폼은 어떤 걸로 하는게 좋을까요? (Chrome 확장프로그램, Web, PC Application)

**Comment by csy1204** [comment]
> 주소록
> 
> * 최근 보낸 주소에 별칭 추가 기능
> 
> 수신자
> 
> * 수신자가 과거에 보낸 이력을 바탕으로 어느 거래소 주소인지 알려주는 기능
> 
> (New) 남기고 싶은 말
> 
> 1. TxData를 이용해서 상대방에게 남기고 싶은 말 적기, 한글을 Hex로 변환하기만 하면 될 거 같아요
> 2. 다른 사람도 모두 볼 수 있다는게 단점아닌 단점
> 
> 거창하기보단 정말 꼭 필요한 걸 만든다는게 좋은 것 같아요. 거기에 재밌고 간단한 기능정도만 ㅎㅎ
> 플랫폼은 어떤 걸로 하는게 좋을까요? (Chrome 확장프로그램, Web, PC Application)

**Comment by jongkwang** [comment]
같은 생각 입니다.

- "이더리움 기본 지갑 보다 편해서 사용해요" 이런 말이 나오면 좋겠어요
- 아직 의견 수렴 단계 이니까, 많이 코멘트 남겨주세요~

**Comment by poweruse** [comment]
주소록 기능 괜찮네요. 
그리고 보면 뱅킹앱에서 아이디어가 많이 나올듯 싶기도 하네요

**Comment by jongkwang** [comment]
## 결정사항

- 10월 1일 회의에 의해
  - Metamask 개선과
  - Wallet Module 개발로 기획을 확정 합니다
- 회의록 : https://github.com/etherstudy/interface/wiki/%ED%9A%8C%EC%9D%98%EB%A1%9D-2018.10.01-%EA%B8%B0%ED%9A%8D%EB%AF%B8%ED%8C%85-and-Infura

이슈를 Close 합니다.
